[package]
name = "searust_core"
version = "0.1.0"
authors = ["Cel Skeggs <git@celskeggs.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
