#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

# special commands:
#   make menuconfig
#   make silentoldconfig
#   make simulate-ia32

all: common kernel_elf

include .config
include tools/common/project.mk
